'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ConsoleEnigmaMachine.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;plugboard&gt;
        '''	&lt;mapping source=&quot;A&quot; destination=&quot;Z&quot; /&gt;
        '''	&lt;mapping source=&quot;Z&quot; destination=&quot;A&quot; /&gt;
        '''&lt;/plugboard&gt;.
        '''</summary>
        Friend ReadOnly Property plugboard() As String
            Get
                Return ResourceManager.GetString("plugboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;reflectors&gt;
        '''	&lt;reflector id=&quot;B&quot; wiring=&quot;YRUHQSLDPXNGOKMIEBFZCWVJAT&quot;/&gt;
        '''	&lt;reflector id=&quot;C&quot; wiring=&quot;FVPJIAOYEDRZXWGCTKUQSBNMHL&quot;/&gt;
        '''	&lt;reflector id=&quot;B-thin&quot; wiring=&quot;ENKQAUYWJICOPBLMDXZVFTHRGS&quot;/&gt;
        '''	&lt;reflector id=&quot;C-thin&quot; wiring=&quot;RDOBJNTKVEHMLFCWZAXGYIPSUQ&quot;/&gt;
        '''&lt;/reflectors&gt;.
        '''</summary>
        Friend ReadOnly Property reflectors() As String
            Get
                Return ResourceManager.GetString("reflectors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;rotors&gt;
        '''	&lt;!-- Wehrmacht / Luftwaffe rotors --&gt;
        '''	&lt;rotor id=&quot;I&quot; notch=&quot;Q&quot; wiring=&quot;EKMFLGDQVZNTOWYHXUSPAIBRCJ&quot;/&gt;
        '''	&lt;rotor id=&quot;II&quot; notch=&quot;E&quot; wiring=&quot;AJDKSIRUXBLHWTMCQGZNPYFVOE&quot;/&gt;
        '''	&lt;rotor id=&quot;III&quot; notch=&quot;V&quot; wiring=&quot;BDFHJLCPRTXVZNYEIWGAKMUSQO&quot;/&gt;
        '''	&lt;rotor id=&quot;IV&quot; notch=&quot;J&quot; wiring=&quot;ESOVPZJAYQUIRHXLNFTGKDCMWB&quot;/&gt;
        '''	&lt;rotor id=&quot;V&quot; notch=&quot;Z&quot; wiring=&quot;VZBRGITYUPSDNHLXAWMJQOFECK&quot;/&gt;
        '''	
        '''	&lt;!-- Kriegsmarine extra rotors --&gt;
        '''	&lt;rotor id=&quot;VI&quot; notch=&quot;ZM&quot; wiring=&quot;JPGVOUMFYQBENHZRDKASXLI [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property rotors() As String
            Get
                Return ResourceManager.GetString("rotors", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
