'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ConsoleEnigmaMachine.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usage: --D &lt;ciphertext&gt;,&lt;pos1&gt;,&lt;pos2&gt;,&lt;pos3&gt;.
        '''</summary>
        Public Shared ReadOnly Property strDecryptSyntax() As String
            Get
                Return ResourceManager.GetString("strDecryptSyntax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''GERMAN ENIGMA MACHINE v2 COMMAND LINE
        '''-------------------------------------
        '''You are currently in EASY mode of operation.
        '''The machine will auto reset after encrypting text.
        '''To switch to HISTORICALLY ACCURATE mode type: &apos;--MODE REAL&apos;
        '''═══════════════════════
        '''The Enigma Commands: --E, --D, --F, --R, --MODE, --Q
        '''To ENCRYPT a message: &apos;--E &lt;msg to encrypt&gt;&apos;.
        '''To DECRYPT a cipher text: &apos;--D &lt;encrypted msg&gt;, rotor 1 settings, r2, r3&apos;
        '''To DISABLE grouping the cipher text in sets of 5: &apos;--F&apos;.
        '''To RESET the [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property strEasyMode() As String
            Get
                Return ResourceManager.GetString("strEasyMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usage: --E &lt;plaintext message&gt;.
        '''</summary>
        Public Shared ReadOnly Property strEncryptSyntax() As String
            Get
                Return ResourceManager.GetString("strEncryptSyntax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Please enter a numeric value..
        '''</summary>
        Public Shared ReadOnly Property strErrNumeric() As String
            Get
                Return ResourceManager.GetString("strErrNumeric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Please enter a value between 0 and 25..
        '''</summary>
        Public Shared ReadOnly Property strErrRotorValues() As String
            Get
                Return ResourceManager.GetString("strErrRotorValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter some text to encrypt..
        '''</summary>
        Public Shared ReadOnly Property strInputNull() As String
            Get
                Return ResourceManager.GetString("strInputNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -------------------------------------.
        '''</summary>
        Public Shared ReadOnly Property strLine() As String
            Get
                Return ResourceManager.GetString("strLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --- Enigma Machine Settings ---.
        '''</summary>
        Public Shared ReadOnly Property strMachineInit() As String
            Get
                Return ResourceManager.GetString("strMachineInit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown mode. Use: --MODE EASY or --MODE REAL.
        '''</summary>
        Public Shared ReadOnly Property strModeCmdErr() As String
            Get
                Return ResourceManager.GetString("strModeCmdErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mode set to EASY (auto-reset and simplified use)..
        '''</summary>
        Public Shared ReadOnly Property strModeCmdEZ() As String
            Get
                Return ResourceManager.GetString("strModeCmdEZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mode set to REALISTIC (manual resets and full control)..
        '''</summary>
        Public Shared ReadOnly Property strModeCmdReal() As String
            Get
                Return ResourceManager.GetString("strModeCmdReal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''DEUTSCHE ENIGMA-MASCHINE v2 EINGABEAUFFORDERUNG
        '''-------------------------------------
        '''You are currently in REAL mode of operation.
        '''The machine will not auto reset after encrypting text.
        '''To switch to EASY mode type: &apos;--MODE EASY&apos;
        '''═══════════════════════
        '''Die Enigma-Befehle: --E, --D, --F, --R, --MODE, --Q
        '''So VERSCHLÜSSELN Sie eine Nachricht: &apos;--E &lt;zu verschlüsselnde Nachricht&gt;&apos;.
        '''So ENTSCHLÜSSELN Sie einen Geheimtext: &apos;--D &lt;verschlüsselte Nachricht&gt;, Rotor 1-Einstellungen, R2, R3&apos;.
        '''Um die Gruppier [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property strNotEasyMode() As String
            Get
                Return ResourceManager.GetString("strNotEasyMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rotor {0} successfully adjusted..
        '''</summary>
        Public Shared ReadOnly Property strNoteSettleOK() As String
            Get
                Return ResourceManager.GetString("strNoteSettleOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Note: Rotor {0} settled at position {1} (slight misalignment)..
        '''</summary>
        Public Shared ReadOnly Property strNoteSettleRotor() As String
            Get
                Return ResourceManager.GetString("strNoteSettleRotor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to === ENIGMA MACHINE CONFIGURATION ===
        '''Enter rotation settings for each rotor (0-25).
        '''These values represent the initial position of each rotor.
        '''---------------------------------------.
        '''</summary>
        Public Shared ReadOnly Property strPreRotRotors() As String
            Get
                Return ResourceManager.GetString("strPreRotRotors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pre-rotate rotor {0} (0-25): .
        '''</summary>
        Public Shared ReadOnly Property strPromRotorPos() As String
            Get
                Return ResourceManager.GetString("strPromRotorPos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quitting Enigma v2....
        '''</summary>
        Public Shared ReadOnly Property strQuit() As String
            Get
                Return ResourceManager.GetString("strQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resetting machine rotors....
        '''</summary>
        Public Shared ReadOnly Property strReset() As String
            Get
                Return ResourceManager.GetString("strReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Previous rotor settings were not saved, must reset manually..
        '''</summary>
        Public Shared ReadOnly Property strSavedPosErr() As String
            Get
                Return ResourceManager.GetString("strSavedPosErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ring Settings: (not exposed)
        '''Plugboard: (not available)
        '''--------------------------------.
        '''</summary>
        Public Shared ReadOnly Property strSettingsNA() As String
            Get
                Return ResourceManager.GetString("strSettingsNA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ---------------------------------------
        '''Rotors have been successfully pre-rotated as follows: .
        '''</summary>
        Public Shared ReadOnly Property strSuccessRot() As String
            Get
                Return ResourceManager.GetString("strSuccessRot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Poor electrical contact detected in rotor {0}.
        '''This may cause occasional encryption errors..
        '''</summary>
        Public Shared ReadOnly Property strWarnEC() As String
            Get
                Return ResourceManager.GetString("strWarnEC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Slight resistance detected when setting rotor {0}.
        '''Attempting to adjust....
        '''</summary>
        Public Shared ReadOnly Property strWarnResistRotors() As String
            Get
                Return ResourceManager.GetString("strWarnResistRotors", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
